In [1]:
import torch
print(torch.__version__)

2.2.1+cu121


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


##Introduction to Tensors

###Creating tensors

In [3]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#Get tensor back as Python int
scalar.item()

7

In [6]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
#TENSOR
TENSOR =torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

### Why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Start with random numbers --> Look at data --> update random numbers --> look at data --> update random numbers

torch random tensor - interval of [0,1)

In [17]:
# Create a random tensors of size (3,4)
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.3233, 0.5189, 0.1142, 0.0581],
         [0.6217, 0.6514, 0.7799, 0.8905],
         [0.1451, 0.3773, 0.0830, 0.7786]]])

In [18]:
random_tensor.ndim

3

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, colour channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [20]:
torch.rand(size=(3,3))

tensor([[0.0298, 0.3496, 0.5857],
        [0.4956, 0.7047, 0.9665],
        [0.4039, 0.0264, 0.5225]])

### Zeros and ones

In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [24]:
one_to_ten=torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
torch.arange(start=1, end= 1000, step=50)

tensor([  1,  51, 101, 151, 201, 251, 301, 351, 401, 451, 501, 551, 601, 651,
        701, 751, 801, 851, 901, 951])

In [26]:
# Creating tensors like
ten_zeros= torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note**: Tensor datatypes is one of the 3 big error you'll run into with PyTorch & Deep Learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tesnors not on the right device


In [27]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, #  what datatype is the tensor (e.g. float32 or float16)
                               device=None, # what device is your tensor on
                               requires_grad= True # whether or not to track gradient with this tensors operation
                               )
float_32_tensor.dtype

torch.float32

In [28]:
float_16_tensor= float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16, grad_fn=<ToCopyBackward0>)

### Getting infromation from tensors (tensor attributes)
 1. to get datatype from a tensor, can use tensor.dtype
 2. to get shape from a tensor, can use tensor.shape
 3. to get device from a tensor, can use tensor.device

In [29]:
# Create a tensor
some_tensor= torch.rand(3,4)
some_tensor


tensor([[0.9063, 0.0399, 0.4070, 0.5352],
        [0.2314, 0.2775, 0.8254, 0.2688],
        [0.3423, 0.7924, 0.1137, 0.9723]])

In [30]:
#find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9063, 0.0399, 0.4070, 0.5352],
        [0.2314, 0.2775, 0.8254, 0.2688],
        [0.3423, 0.7924, 0.1137, 0.9723]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors (tensor operations)

Tensor operations include:

*Addition

*Subtraction

*Multiplication (element-wise)

*Division

*Matrix multiplication

In [31]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor +10

tensor([11, 12, 13])

In [32]:
# Multiply tensor by 10
tensor* 10

tensor([10, 20, 30])

In [33]:
# Subtarct 10
tensor - 10

tensor([-9, -8, -7])

In [34]:
# Try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [35]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [36]:
# Element wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [37]:
# Matrix multiplication (Dot product)
torch.matmul(tensor,tensor)

tensor(14)

In [38]:
tensor @ tensor

tensor(14)

For matrix multiplication

**Note**:
1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimensions

In [39]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.mm(tensor_A,tensor_B) # torch.mm is the same for torch.matmul


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [40]:
# To fix out tensor shape issues, we can manipulate the shape of one of our tensors using a transpose

In [41]:
tensor_B.T , tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [42]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min,max,mean,sum,etc (tensor aggregation)

In [43]:
#Create a tensor
x = torch.arange(0,100,10)
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [44]:
#Find the min
torch.min(x),x.min()

(tensor(0), tensor(0))

In [45]:
#Find the max
torch.max(x),x.max()

(tensor(90), tensor(90))

In [46]:
#Find the mean - torch.mean() requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [47]:
# Find the sum
torch.sum(x)

tensor(450)

In [48]:
x.argmin()

tensor(0)

In [49]:
x.argmax()

tensor(9)

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - rehshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimensi to a target tensor
* Permute - return a view of the input with dimensions permuted(swapped) in a certain way

In [50]:
x=torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [51]:
#Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape


(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [52]:
# Change the view
z= x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [53]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input )
z[:,0]=5
z,x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [54]:
# Stack tensors on top of each other
x_stacked = torch.stack ([x,x,x,x], dim=1)
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [55]:
# torch.squeeze() - removes all single dimensions from a tensor
x_reshaped


tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [56]:
x_reshaped.shape

torch.Size([1, 9])

In [57]:
x_squeezed=x_reshaped.squeeze()
x_squeezed

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
x_reshaped.squeeze().shape

torch.Size([9])

In [59]:
# torch.unsqueeze() - adds a single dimensions to a target tensor at a specific dim
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [62]:
#torch.permute()- rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) #{height, width, colour_channels]}

# Permute the original tensor to arrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing(selecting data from tensors)
 Indexing with PyTorch is similar to indexing with Numpy

In [64]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape, x.ndim


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]),
 3)

In [65]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [66]:
x[0][0]

tensor([1, 2, 3])

In [67]:
x[0][0][0]

tensor(1)

In [68]:
x[0][1][1]

tensor(5)

In [69]:
x[0][2][2]

tensor(9)

In [70]:
# You can also use ':' to select all of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [71]:
# Get all values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [72]:
x[:,1,1]

tensor([5])

In [73]:
x[0,0,:]

tensor([1, 2, 3])

In [74]:
x[0,:,2]

tensor([3, 6, 9])

In [75]:
x[0,0,2]

tensor(3)

### PyTorch tensors & Numpy

Numpy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `tensor.from_numpy(ndarray)`

* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [76]:
import torch
import numpy as np

array =np.arange(1,8)
tensor = torch.from_numpy(array)
array, tensor

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [77]:
array.dtype

dtype('int64')

In [78]:
tensor.dtype

torch.int64

In [80]:
tensor.type(torch.float32) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatpe of float64 unless specified otherwise

tensor([1., 2., 3., 4., 5., 6., 7.])

In [81]:
array = array +1
array, tensor

(array([2, 3, 4, 5, 6, 7, 8]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [83]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
numpy_tensor, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([1., 1., 1., 1., 1., 1., 1.]))

In [86]:
tensor = tensor +1
numpy_tensor, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([4., 4., 4., 4., 4., 4., 4.]))

### Reproducibility ( trying to take random out of random)

In short how a neural network learns:

 `start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again....`

 To reduce the randomness in neural networks and PyTorch comes the concept of **random seed**

 Essentially what the random seed does is "flavour" the randomness  

In [87]:
import torch

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA+ NVIDIA hardware + PyTorch working behind the scenes

In [89]:
# Easiest - Use Google Colab for a free GPU
# Use your own GPU - takes a little bit of setup and requires the investement of purchasing a GPU
# Use cloud computing - GCP, AWS , Azure, these services allow you to rent the computer on the cloud and access them

In [2]:
!nvidia-smi

Fri May 10 14:59:49 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   64C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [3]:
## Check for GPU access with PyTorch

import torch
torch.cuda.is_available()

True

In [4]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
# Putting tensors (and models) on the GPUs

tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu, tensor_on_gpu.device)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0') cuda:0


In [6]:
# Moving tensors back to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [7]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')